<h1>  Part 1 Preparing The Data </h1>

In [1]:
import numpy as np
import pandas as pd
import requests

weburl = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

<h1>  install soup library  </h1>

In [3]:

!pip install BeautifulSoup4
from bs4 import BeautifulSoup
soup = BeautifulSoup(weburl,'html.parser')

Requirement already satisfied: BeautifulSoup4 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.9.1)
Requirement already satisfied: soupsieve>1.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from BeautifulSoup4) (2.0.1)

In [4]:

table=soup.find('table')

In [5]:
column_names = ['Postalcode','Borough','Neighborhood']
df = pd.DataFrame(columns = column_names)

In [6]:
df

Empty DataFrame
Columns: [Postalcode, Borough, Neighborhood]
Index: []

<h1>  take the contents from the site   </h1>

In [8]:
for tr_c in table.find_all('tr'):
    row_data=[]
    for td_c in tr_c.find_all('td'):
        row_data.append(td_c.text.strip())
    if len(row_data)==3:
        df.loc[len(df)] = row_data

In [10]:
df.head(11)

   Postalcode           Borough                                 Neighborhood
0         M1A      Not assigned                                 Not assigned
1         M2A      Not assigned                                 Not assigned
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7         M8A      Not assigned                                 Not assigned
8         M9A         Etobicoke      Islington Avenue, Humber Valley Village
9         M1B       Scarborough                               Malvern, Rouge
10        M2B      Not assigned                                 Not assigned

In [11]:

df_index = df[df.Borough != 'Not assigned']

In [12]:

df_index.head(5)

  Postalcode           Borough                                 Neighborhood
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

<h1>   joining  </h1>

In [16]:
result = df_index.groupby(['Postalcode','Borough'], sort = False).agg( ', '.join)

In [17]:

df_new=result.reset_index()
df_new.head(15)

,Postalcode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
6,M1B,Scarborough,"Malvern, Rouge"
7,M3B,North York,Don Mills
8,M4B,East York,"Parkview Hill, Woodbine Gardens"
9,M5B,Downtown Toronto,"Garden District, Ryerson"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
13,M3C,North York,Don Mills
14,M4C,East York,Woodbine Heights

In [18]:
df

,Postalcode,Borough,Neighborhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned